// <auto-generated />
namespace Dominos.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class P_SC_M : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(P_SC_M));
        
        string IMigrationMetadata.Id
        {
            get { return "201703241849311_P_SC_M"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
