//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IProductWebService", Namespace="http://tempuri.org/")]
public partial class ProductWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetProductsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetProductByIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetShoppingCartItemsOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddShoppingCartOperationCompleted;
    
    private System.Threading.SendOrPostCallback SetShoppingCartQuantityOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetProductImageByIdOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetProductImageWithoutBinaryOperationCompleted;
    
    /// <remarks/>
    public ProductWebService() {
        this.Url = "http://localhost:53565/ProductWebService.svc";
    }
    
    /// <remarks/>
    public event GetProductsCompletedEventHandler GetProductsCompleted;
    
    /// <remarks/>
    public event GetProductByIdCompletedEventHandler GetProductByIdCompleted;
    
    /// <remarks/>
    public event GetShoppingCartItemsCompletedEventHandler GetShoppingCartItemsCompleted;
    
    /// <remarks/>
    public event AddShoppingCartCompletedEventHandler AddShoppingCartCompleted;
    
    /// <remarks/>
    public event SetShoppingCartQuantityCompletedEventHandler SetShoppingCartQuantityCompleted;
    
    /// <remarks/>
    public event GetProductImageByIdCompletedEventHandler GetProductImageByIdCompleted;
    
    /// <remarks/>
    public event GetProductImageWithoutBinaryCompletedEventHandler GetProductImageWithoutBinaryCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductWebService/GetProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dominos.WCFService.DTO")]
    public ProductDTO[] GetProducts() {
        object[] results = this.Invoke("GetProducts", new object[0]);
        return ((ProductDTO[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetProducts(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetProducts", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ProductDTO[] EndGetProducts(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ProductDTO[])(results[0]));
    }
    
    /// <remarks/>
    public void GetProductsAsync() {
        this.GetProductsAsync(null);
    }
    
    /// <remarks/>
    public void GetProductsAsync(object userState) {
        if ((this.GetProductsOperationCompleted == null)) {
            this.GetProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsOperationCompleted);
        }
        this.InvokeAsync("GetProducts", new object[0], this.GetProductsOperationCompleted, userState);
    }
    
    private void OnGetProductsOperationCompleted(object arg) {
        if ((this.GetProductsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProductsCompleted(this, new GetProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductWebService/GetProductById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ProductDTO GetProductById(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
        object[] results = this.Invoke("GetProductById", new object[] {
                    id,
                    idSpecified});
        return ((ProductDTO)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetProductById(int id, bool idSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetProductById", new object[] {
                    id,
                    idSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public ProductDTO EndGetProductById(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ProductDTO)(results[0]));
    }
    
    /// <remarks/>
    public void GetProductByIdAsync(int id, bool idSpecified) {
        this.GetProductByIdAsync(id, idSpecified, null);
    }
    
    /// <remarks/>
    public void GetProductByIdAsync(int id, bool idSpecified, object userState) {
        if ((this.GetProductByIdOperationCompleted == null)) {
            this.GetProductByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductByIdOperationCompleted);
        }
        this.InvokeAsync("GetProductById", new object[] {
                    id,
                    idSpecified}, this.GetProductByIdOperationCompleted, userState);
    }
    
    private void OnGetProductByIdOperationCompleted(object arg) {
        if ((this.GetProductByIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProductByIdCompleted(this, new GetProductByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductWebService/GetShoppingCartItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dominos.WCFService.DTO")]
    public ShoppingCartDTO[] GetShoppingCartItems(int userId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool userIdSpecified) {
        object[] results = this.Invoke("GetShoppingCartItems", new object[] {
                    userId,
                    userIdSpecified});
        return ((ShoppingCartDTO[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetShoppingCartItems(int userId, bool userIdSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetShoppingCartItems", new object[] {
                    userId,
                    userIdSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public ShoppingCartDTO[] EndGetShoppingCartItems(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ShoppingCartDTO[])(results[0]));
    }
    
    /// <remarks/>
    public void GetShoppingCartItemsAsync(int userId, bool userIdSpecified) {
        this.GetShoppingCartItemsAsync(userId, userIdSpecified, null);
    }
    
    /// <remarks/>
    public void GetShoppingCartItemsAsync(int userId, bool userIdSpecified, object userState) {
        if ((this.GetShoppingCartItemsOperationCompleted == null)) {
            this.GetShoppingCartItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShoppingCartItemsOperationCompleted);
        }
        this.InvokeAsync("GetShoppingCartItems", new object[] {
                    userId,
                    userIdSpecified}, this.GetShoppingCartItemsOperationCompleted, userState);
    }
    
    private void OnGetShoppingCartItemsOperationCompleted(object arg) {
        if ((this.GetShoppingCartItemsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetShoppingCartItemsCompleted(this, new GetShoppingCartItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductWebService/AddShoppingCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void AddShoppingCart(int productId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool productIdSpecified, int userId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool userIdSpecified, int quantity, [System.Xml.Serialization.XmlIgnoreAttribute()] bool quantitySpecified, out bool AddShoppingCartResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool AddShoppingCartResultSpecified) {
        object[] results = this.Invoke("AddShoppingCart", new object[] {
                    productId,
                    productIdSpecified,
                    userId,
                    userIdSpecified,
                    quantity,
                    quantitySpecified});
        AddShoppingCartResult = ((bool)(results[0]));
        AddShoppingCartResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddShoppingCart(int productId, bool productIdSpecified, int userId, bool userIdSpecified, int quantity, bool quantitySpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddShoppingCart", new object[] {
                    productId,
                    productIdSpecified,
                    userId,
                    userIdSpecified,
                    quantity,
                    quantitySpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndAddShoppingCart(System.IAsyncResult asyncResult, out bool AddShoppingCartResult, out bool AddShoppingCartResultSpecified) {
        object[] results = this.EndInvoke(asyncResult);
        AddShoppingCartResult = ((bool)(results[0]));
        AddShoppingCartResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void AddShoppingCartAsync(int productId, bool productIdSpecified, int userId, bool userIdSpecified, int quantity, bool quantitySpecified) {
        this.AddShoppingCartAsync(productId, productIdSpecified, userId, userIdSpecified, quantity, quantitySpecified, null);
    }
    
    /// <remarks/>
    public void AddShoppingCartAsync(int productId, bool productIdSpecified, int userId, bool userIdSpecified, int quantity, bool quantitySpecified, object userState) {
        if ((this.AddShoppingCartOperationCompleted == null)) {
            this.AddShoppingCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddShoppingCartOperationCompleted);
        }
        this.InvokeAsync("AddShoppingCart", new object[] {
                    productId,
                    productIdSpecified,
                    userId,
                    userIdSpecified,
                    quantity,
                    quantitySpecified}, this.AddShoppingCartOperationCompleted, userState);
    }
    
    private void OnAddShoppingCartOperationCompleted(object arg) {
        if ((this.AddShoppingCartCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddShoppingCartCompleted(this, new AddShoppingCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductWebService/SetShoppingCartQuantity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SetShoppingCartQuantity(int productId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool productIdSpecified, int userId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool userIdSpecified, int quantity, [System.Xml.Serialization.XmlIgnoreAttribute()] bool quantitySpecified, out bool SetShoppingCartQuantityResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SetShoppingCartQuantityResultSpecified) {
        object[] results = this.Invoke("SetShoppingCartQuantity", new object[] {
                    productId,
                    productIdSpecified,
                    userId,
                    userIdSpecified,
                    quantity,
                    quantitySpecified});
        SetShoppingCartQuantityResult = ((bool)(results[0]));
        SetShoppingCartQuantityResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSetShoppingCartQuantity(int productId, bool productIdSpecified, int userId, bool userIdSpecified, int quantity, bool quantitySpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SetShoppingCartQuantity", new object[] {
                    productId,
                    productIdSpecified,
                    userId,
                    userIdSpecified,
                    quantity,
                    quantitySpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSetShoppingCartQuantity(System.IAsyncResult asyncResult, out bool SetShoppingCartQuantityResult, out bool SetShoppingCartQuantityResultSpecified) {
        object[] results = this.EndInvoke(asyncResult);
        SetShoppingCartQuantityResult = ((bool)(results[0]));
        SetShoppingCartQuantityResultSpecified = ((bool)(results[1]));
    }
    
    /// <remarks/>
    public void SetShoppingCartQuantityAsync(int productId, bool productIdSpecified, int userId, bool userIdSpecified, int quantity, bool quantitySpecified) {
        this.SetShoppingCartQuantityAsync(productId, productIdSpecified, userId, userIdSpecified, quantity, quantitySpecified, null);
    }
    
    /// <remarks/>
    public void SetShoppingCartQuantityAsync(int productId, bool productIdSpecified, int userId, bool userIdSpecified, int quantity, bool quantitySpecified, object userState) {
        if ((this.SetShoppingCartQuantityOperationCompleted == null)) {
            this.SetShoppingCartQuantityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetShoppingCartQuantityOperationCompleted);
        }
        this.InvokeAsync("SetShoppingCartQuantity", new object[] {
                    productId,
                    productIdSpecified,
                    userId,
                    userIdSpecified,
                    quantity,
                    quantitySpecified}, this.SetShoppingCartQuantityOperationCompleted, userState);
    }
    
    private void OnSetShoppingCartQuantityOperationCompleted(object arg) {
        if ((this.SetShoppingCartQuantityCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SetShoppingCartQuantityCompleted(this, new SetShoppingCartQuantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductWebService/GetProductImageById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public MediaDTO GetProductImageById(int imageId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool imageIdSpecified) {
        object[] results = this.Invoke("GetProductImageById", new object[] {
                    imageId,
                    imageIdSpecified});
        return ((MediaDTO)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetProductImageById(int imageId, bool imageIdSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetProductImageById", new object[] {
                    imageId,
                    imageIdSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public MediaDTO EndGetProductImageById(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MediaDTO)(results[0]));
    }
    
    /// <remarks/>
    public void GetProductImageByIdAsync(int imageId, bool imageIdSpecified) {
        this.GetProductImageByIdAsync(imageId, imageIdSpecified, null);
    }
    
    /// <remarks/>
    public void GetProductImageByIdAsync(int imageId, bool imageIdSpecified, object userState) {
        if ((this.GetProductImageByIdOperationCompleted == null)) {
            this.GetProductImageByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductImageByIdOperationCompleted);
        }
        this.InvokeAsync("GetProductImageById", new object[] {
                    imageId,
                    imageIdSpecified}, this.GetProductImageByIdOperationCompleted, userState);
    }
    
    private void OnGetProductImageByIdOperationCompleted(object arg) {
        if ((this.GetProductImageByIdCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProductImageByIdCompleted(this, new GetProductImageByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductWebService/GetProductImageWithoutBinary", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public MediaDTO GetProductImageWithoutBinary(int imageId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool imageIdSpecified) {
        object[] results = this.Invoke("GetProductImageWithoutBinary", new object[] {
                    imageId,
                    imageIdSpecified});
        return ((MediaDTO)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetProductImageWithoutBinary(int imageId, bool imageIdSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetProductImageWithoutBinary", new object[] {
                    imageId,
                    imageIdSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public MediaDTO EndGetProductImageWithoutBinary(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MediaDTO)(results[0]));
    }
    
    /// <remarks/>
    public void GetProductImageWithoutBinaryAsync(int imageId, bool imageIdSpecified) {
        this.GetProductImageWithoutBinaryAsync(imageId, imageIdSpecified, null);
    }
    
    /// <remarks/>
    public void GetProductImageWithoutBinaryAsync(int imageId, bool imageIdSpecified, object userState) {
        if ((this.GetProductImageWithoutBinaryOperationCompleted == null)) {
            this.GetProductImageWithoutBinaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductImageWithoutBinaryOperationCompleted);
        }
        this.InvokeAsync("GetProductImageWithoutBinary", new object[] {
                    imageId,
                    imageIdSpecified}, this.GetProductImageWithoutBinaryOperationCompleted, userState);
    }
    
    private void OnGetProductImageWithoutBinaryOperationCompleted(object arg) {
        if ((this.GetProductImageWithoutBinaryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProductImageWithoutBinaryCompleted(this, new GetProductImageWithoutBinaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dominos.WCFService.DTO")]
public partial class ProductDTO {
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private System.Nullable<int> imageIdField;
    
    private bool imageIdFieldSpecified;
    
    private string imageUrlField;
    
    private decimal priceField;
    
    private bool priceFieldSpecified;
    
    private string titleField;
    
    /// <remarks/>
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> ImageId {
        get {
            return this.imageIdField;
        }
        set {
            this.imageIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ImageIdSpecified {
        get {
            return this.imageIdFieldSpecified;
        }
        set {
            this.imageIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ImageUrl {
        get {
            return this.imageUrlField;
        }
        set {
            this.imageUrlField = value;
        }
    }
    
    /// <remarks/>
    public decimal Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PriceSpecified {
        get {
            return this.priceFieldSpecified;
        }
        set {
            this.priceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dominos.WCFService.DTO")]
public partial class MediaDTO {
    
    private byte[] fileBinaryField;
    
    private string fileContentTypeField;
    
    private string fileExtensionField;
    
    private string fileNameField;
    
    private int fileSizeField;
    
    private bool fileSizeFieldSpecified;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
    public byte[] FileBinary {
        get {
            return this.fileBinaryField;
        }
        set {
            this.fileBinaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FileContentType {
        get {
            return this.fileContentTypeField;
        }
        set {
            this.fileContentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FileExtension {
        get {
            return this.fileExtensionField;
        }
        set {
            this.fileExtensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    public int FileSize {
        get {
            return this.fileSizeField;
        }
        set {
            this.fileSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FileSizeSpecified {
        get {
            return this.fileSizeFieldSpecified;
        }
        set {
            this.fileSizeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dominos.WCFService.DTO")]
public partial class ShoppingCartDTO {
    
    private ProductDTO productField;
    
    private int productIdField;
    
    private bool productIdFieldSpecified;
    
    private int quantityField;
    
    private bool quantityFieldSpecified;
    
    private int userIdField;
    
    private bool userIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ProductDTO Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    public int ProductId {
        get {
            return this.productIdField;
        }
        set {
            this.productIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProductIdSpecified {
        get {
            return this.productIdFieldSpecified;
        }
        set {
            this.productIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QuantitySpecified {
        get {
            return this.quantityFieldSpecified;
        }
        set {
            this.quantityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UserIdSpecified {
        get {
            return this.userIdFieldSpecified;
        }
        set {
            this.userIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void GetProductsCompletedEventHandler(object sender, GetProductsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ProductDTO[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ProductDTO[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void GetProductByIdCompletedEventHandler(object sender, GetProductByIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProductByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetProductByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ProductDTO Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ProductDTO)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void GetShoppingCartItemsCompletedEventHandler(object sender, GetShoppingCartItemsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetShoppingCartItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetShoppingCartItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ShoppingCartDTO[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ShoppingCartDTO[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void AddShoppingCartCompletedEventHandler(object sender, AddShoppingCartCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddShoppingCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AddShoppingCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool AddShoppingCartResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool AddShoppingCartResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void SetShoppingCartQuantityCompletedEventHandler(object sender, SetShoppingCartQuantityCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SetShoppingCartQuantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SetShoppingCartQuantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool SetShoppingCartQuantityResult {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public bool SetShoppingCartQuantityResultSpecified {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void GetProductImageByIdCompletedEventHandler(object sender, GetProductImageByIdCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProductImageByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetProductImageByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public MediaDTO Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MediaDTO)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void GetProductImageWithoutBinaryCompletedEventHandler(object sender, GetProductImageWithoutBinaryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProductImageWithoutBinaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetProductImageWithoutBinaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public MediaDTO Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MediaDTO)(this.results[0]));
        }
    }
}
